version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  backend:
    build: ./api
    depends_on:
      - "mongo"

  frontend:
    build:
      context: ./app
    ports:
      - "4000:80"
    depends_on:
      - "backend"

volumes:
  mongo:
    driver_opts:
      type: tmpfs
      device: tmpfs
